version: "3.7"
services:
  app:
    build:
      args:
        user: ASUS
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: videosapi
    container_name: videosapi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - videosapi

  db:
    image: mysql:5.7
    container_name: videosapi-db
    restart: unless-stopped
    ports:
      - 6672:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - videosapi

  nginx:
    image: nginx:1.17-alpine
    container_name: videosapi-nginx
    restart: unless-stopped
    ports:
      - 6673:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - videosapi

networks:
  videosapi:
    driver: bridge
